theme = "congo"
baseURL = 'https://varomix.github.io/'
locale = 'en-us'
title = 'Varo Castaneda'


[params]
  colorScheme = "avocado"
  defaultAppearance = "dark"
  autoSwitchAppearance = false

[params.homepage]
  layout = "profile"

[params.author]
name = "Varo Castaneda"
image = "img/varo.jpg"
headline = "Software Engineer | Technical Artist"
bio = "I like Pixel Tacos!"
links = [
    { email = "mailto:varomix@varomix.net" },
    { linkedin = "https://www.linkedin.com/in/varomix" },
    { github = "https://www.github.com/varomix" },
    { youtube = "https://www.youtube.com/watch?v=XU5LCUP25RY" },
]

[caches]
[caches.images]
dir = ':cacheDir/images'
